name: Publish NuGet Package

on:
  release:
    types: [  ]
  push:
    branches: [ release ]

jobs:
  build:

    runs-on: ubuntu-latest
    environment: Testing

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: dotnet test --no-build --verbosity normal
      
    - name: Find NuGet packages
      id: find_packages
      run: |
        nupkg_files=$(find . -name '*.nupkg')
        nupkg_files="${nupkg_files//$'\n'/;}"
        echo "nupkg_files=$nupkg_files" >> $GITHUB_ENV
    - name: Push NuGet packages
      run: |
        IFS=';' read -ra packages <<< "${{ env.nupkg_files }}"
        for pkg in "${packages[@]}"; do
          dotnet nuget push "$pkg" --source 'https://api.nuget.org/v3/index.json' --api-key ${{ secrets.NUGET_API_KEY }}
        done
    